application:
  name:abs-service

server:
  port: 8086

spring:
  application:
    name: abs-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    enabled: 'true'
    change-log: classpath:liquibase/changelog-master.yml
  jpa:
    show-sql: 'true' 