package ru.aston.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.util.UUID;

@Entity
@Table(name = "card")
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Data
public class Card {

    /**
     * Card primary key. Generated by incrementation strategy
     */

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * UUID of Card.
     * Used to connect to other services.
     * Must be unique and cannot be null.
     */
    private UUID uuid;

    /**
     * UUID of Client.
     * Used to connect to other services.
     * Must be unique and cannot be null.
     */
    private UUID clientUuid;

    /**
     * Number of client account witch AbsCard belongs to.
     * Cannot be null.
     */

    private String accountNumber;

    /**
     * Number of card - VARCHAR (16).
     * Cannot be null.
     */
    private String cardNumber;

    /**
     * The limit of card transactions - DECIMAL(19, 4).
     */
    private Double transactionLimit;

    /**
     * The status of card.
     */
    private String status;

    /**
     * Validity period of new card.
     */
    @Transient
    private Integer cardDuration;

    /**
     * Card expiration DATE.
     * Cannot be null.
     */
    private LocalDate expirationDate;

    /**
     * Name of card-holder.
     * Cannot be null.
     */
    private String holderName;

}
